---
title: "About Me"
author: "Matthew Hoyle"
date: "March 2, 2020"
output: html_document
---

Hello!

I'm Matthew Hoyle.

I'm a Junior double-majoring in Statistics and Astronomy at the University of Illinois at Urbana-Champaign. 

Aside from my studies, I am also currently a course assistant for STAT 200: Statistical Analysis as well as a social media data analyst intern for the University of Illinois Student Money Management Center. Within my position at the Student Money Management Center, I have gained valuable experience cleaning, analyzing, and visualizing data from Twitter, Facebook, and Instagram, as well as create automation programs for said processes. So far my work has allowed us to implement multiple changes to our posting methods in order to optimize engagement.

I am always hungry for more knowledge, which has led me to live a life where I am always looking for ways to learn and improve, whether that be within STEM or on a more personal level. If you ever want to chat and are in need an ice breaker, in my spare time I enjoy playing video games, watching the latest Tarantino movies, and being involved in the College Diabetes Network.

Feel free to reach out on [LinkedIn](https://www.linkedin.com/in/matthew-hoyle-0b33831a3/), or email me directly at mhoyle2@illinois.edu.











