---
title: "About Me"
author: "Matthew Hoyle"
date: "March 2, 2020"
output: html_document
---

Hello!

I'm Matthew Hoyle.

I'm a Junior double-majoring in Statistics and Astronomy at the University of Illinois at Urbana-Champaign. 

Aside from my studies, I am also currently a course assistant for STAT 200: Statistical Analysis as well as a social media data analyst intern for the University of Illinois Student Money Management Center. Within my position at the Student Money Management Center, I have gained valuable experience cleaning, analyzing, and visualizing data from Twitter, Facebook, and Instagram, as well as creating automation programs for said processes. So far my work has allowed us to implement multiple changes to our posting methods in order to optimize engagement.

Although my career interests are centered around data analytics, my child-like curiousity and love of discovery is why I am also majoring in astronomy. You can find me in my free time reading science fiction novels or watching documentaries about the great scientists of history (one of my favorites is [The Day After Trinity](https://www.youtube.com/watch?v=Vm5fCxXnK7Y), which details the life of physicist J. Robert Oppenheimer and the Manhatten Project).

If you ever want to chat and are in need an ice breaker, in my spare time I enjoy playing video games, watching Tarantino movies, and being involved in the College Diabetes Network here on campus.

Feel free to reach out on [LinkedIn](https://www.linkedin.com/in/matthew-hoyle-0b33831a3/) or email me directly at mhoyle2@illinois.edu.

>"It always seems impossible, until it is done."
>
>--Nelson Mandela






